### ISSUE TITLE
Currency list

### ISSUE THREAD

**Issue by amirmohsen** [amirmohsen/wealth#4]
Aggregate data from various sources
https://www.npmjs.com/package/currency-symbol-map
https://www.npmjs.com/package/currency-formatter
https://www.npmjs.com/package/currency-codes
https://www.npmjs.com/package/countries-list

**Comment by theninja** [comment]
I'm guessing it will be hard to compete with the data set [CLDR](http://cldr.unicode.org/cldr-features) provides. The main problem is it's so damn big I haven't quite figured out a way to grok or even grab it quickly.

[Wikipedia](https://en.wikipedia.org/wiki/List_of_circulating_currencies) is pretty decent when it comes to up-to-date lists like this as well.

**Comment by amirmohsen** [comment]
I wonder if there's a free api available.

**Comment by amirmohsen** [comment]
Using currency formatter for now.
