### ISSUE TITLE
Money manipulation

### ISSUE THREAD

**Issue by amirmohsen** [amirmohsen/wealth#5]
Existing library:
https://github.com/davidkalosi/js-money

We need to use strings instead of integers unlike this library

**Comment by theninja** [comment]
For representing numbers we could just use a library that does this for us, such as [big-integer](https://github.com/peterolson/BigInteger.js).

Then I suppose we'd have to think about rounding. Do we always round up to the nearest cent? Is this configurable?

**Comment by amirmohsen** [comment]
Good call on big integer.

I've noticed other libraries round by default and offer the choice to override this by providing either ceil or floor

**Comment by amirmohsen** [comment]
https://github.com/MikeMcl/bignumber.js/ used in the end.
